// <auto-generated />
using System;
using FootballResults.Api.Model.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballResults.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260722202411_AddDetailedSquadQualityFields")]
    partial class AddDetailedSquadQualityFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballResults.Api.Model.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ApiKeyCreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("MemberSinceUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyHash")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.EloRatingRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseRating")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("BootstrapSeasonCount")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("HomeAdvantage")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("ImportedHistoricalMatches")
                        .HasColumnType("int");

                    b.Property<decimal>("KFactor")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ProcessedMatches")
                        .HasColumnType("int");

                    b.Property<decimal>("PromotedBaselineRating")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "StartedAtUtc");

                    b.ToTable("EloRatingRuns");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.ExternalTeamMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ExternalSlug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ExternalTeamId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ExternalTeamId")
                        .IsUnique();

                    b.HasIndex("TeamId", "Provider")
                        .IsUnique();

                    b.ToTable("ExternalTeamMappings");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.FormRatingRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EloRatingRunId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MatchCount")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxAdjustment")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("ProcessedTeams")
                        .HasColumnType("int");

                    b.Property<decimal>("Scale")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EloRatingRunId");

                    b.HasIndex("TournamentId", "StartedAtUtc");

                    b.ToTable("FormRatingRuns");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.HistoricalMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<string>("AwayTeamAbbrSnapshot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<string>("AwayTeamLiveScoreId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AwayTeamNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompetitionCountry")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CompetitionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<string>("HomeTeamAbbrSnapshot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<string>("HomeTeamLiveScoreId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("HomeTeamNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("KickoffUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LiveScoreCompetitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LiveScoreEventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RawStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("RegularTimeAwayScore")
                        .HasColumnType("int");

                    b.Property<int?>("RegularTimeHomeScore")
                        .HasColumnType("int");

                    b.Property<string>("RoundInfo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceEndpoint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StageCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LiveScoreEventId")
                        .IsUnique();

                    b.HasIndex("CompetitionName", "KickoffUtc");

                    b.HasIndex("LiveScoreCompetitionId", "KickoffUtc");

                    b.ToTable("HistoricalMatches");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.HistoricalMatchStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayBlockedShots")
                        .HasColumnType("int");

                    b.Property<int?>("AwayCorners")
                        .HasColumnType("int");

                    b.Property<int?>("AwayCounterAttacks")
                        .HasColumnType("int");

                    b.Property<int?>("AwayCrosses")
                        .HasColumnType("int");

                    b.Property<decimal?>("AwayExpectedGoals")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int?>("AwayFouls")
                        .HasColumnType("int");

                    b.Property<int?>("AwayGoalKicks")
                        .HasColumnType("int");

                    b.Property<int?>("AwayGoalkeeperSaves")
                        .HasColumnType("int");

                    b.Property<int?>("AwayOffsides")
                        .HasColumnType("int");

                    b.Property<int?>("AwayPossession")
                        .HasColumnType("int");

                    b.Property<int?>("AwayRedCards")
                        .HasColumnType("int");

                    b.Property<int?>("AwayShotsOffTarget")
                        .HasColumnType("int");

                    b.Property<int?>("AwayShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<int?>("AwayThrowIns")
                        .HasColumnType("int");

                    b.Property<int?>("AwayYellowCards")
                        .HasColumnType("int");

                    b.Property<int?>("AwayYellowRedCards")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("HistoricalMatchId")
                        .HasColumnType("int");

                    b.Property<int?>("HomeBlockedShots")
                        .HasColumnType("int");

                    b.Property<int?>("HomeCorners")
                        .HasColumnType("int");

                    b.Property<int?>("HomeCounterAttacks")
                        .HasColumnType("int");

                    b.Property<int?>("HomeCrosses")
                        .HasColumnType("int");

                    b.Property<decimal?>("HomeExpectedGoals")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int?>("HomeFouls")
                        .HasColumnType("int");

                    b.Property<int?>("HomeGoalKicks")
                        .HasColumnType("int");

                    b.Property<int?>("HomeGoalkeeperSaves")
                        .HasColumnType("int");

                    b.Property<int?>("HomeOffsides")
                        .HasColumnType("int");

                    b.Property<int?>("HomePossession")
                        .HasColumnType("int");

                    b.Property<int?>("HomeRedCards")
                        .HasColumnType("int");

                    b.Property<int?>("HomeShotsOffTarget")
                        .HasColumnType("int");

                    b.Property<int?>("HomeShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<int?>("HomeThrowIns")
                        .HasColumnType("int");

                    b.Property<int?>("HomeYellowCards")
                        .HasColumnType("int");

                    b.Property<int?>("HomeYellowRedCards")
                        .HasColumnType("int");

                    b.Property<string>("LiveScoreEventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("HistoricalMatchId")
                        .IsUnique();

                    b.HasIndex("LiveScoreEventId")
                        .IsUnique();

                    b.ToTable("HistoricalMatchStatistics");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AfterExtraTimeAwayScore")
                        .HasColumnType("int");

                    b.Property<int?>("AfterExtraTimeHomeScore")
                        .HasColumnType("int");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<string>("AwayTeamAbbrSnapshot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<string>("AwayTeamImageSnapshot")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AwayTeamNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ExtraTimeAwayGoals")
                        .HasColumnType("int");

                    b.Property<int?>("ExtraTimeHomeGoals")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<string>("HomeTeamAbbrSnapshot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<string>("HomeTeamImageSnapshot")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HomeTeamNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("KickoffUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastSeenInListType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LastSourceEndpoint")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LiveScoreEventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("MatchUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PenaltyAwayScore")
                        .HasColumnType("int");

                    b.Property<int?>("PenaltyHomeScore")
                        .HasColumnType("int");

                    b.Property<string>("RawStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("RegularTimeAwayScore")
                        .HasColumnType("int");

                    b.Property<int?>("RegularTimeHomeScore")
                        .HasColumnType("int");

                    b.Property<string>("RoundInfo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("StageId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SyncState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LiveScoreEventId")
                        .IsUnique();

                    b.HasIndex("StageId");

                    b.HasIndex("TournamentId", "KickoffUtc");

                    b.HasIndex("TournamentId", "Status");

                    b.HasIndex("TournamentId", "SyncState");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.MatchEloSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AwayActual")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("AwayEloAfter")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("AwayEloBefore")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("AwayEloChange")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("AwayExpected")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int>("EloRatingRunId")
                        .HasColumnType("int");

                    b.Property<decimal>("GoalDifferenceMultiplier")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("HistoricalMatchId")
                        .HasColumnType("int");

                    b.Property<decimal>("HomeActual")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("HomeAdvantageApplied")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("HomeEloAfter")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("HomeEloBefore")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("HomeEloChange")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("HomeExpected")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<decimal>("KFactor")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<DateTimeOffset>("KickoffUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LiveScoreEventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HistoricalMatchId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("EloRatingRunId", "AwayTeamId");

                    b.HasIndex("EloRatingRunId", "HistoricalMatchId")
                        .IsUnique();

                    b.HasIndex("EloRatingRunId", "HomeTeamId");

                    b.HasIndex("EloRatingRunId", "KickoffUtc");

                    b.ToTable("MatchEloSnapshots");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.MatchStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayBlockedShots")
                        .HasColumnType("int");

                    b.Property<int?>("AwayCorners")
                        .HasColumnType("int");

                    b.Property<int?>("AwayCounterAttacks")
                        .HasColumnType("int");

                    b.Property<int?>("AwayCrosses")
                        .HasColumnType("int");

                    b.Property<decimal?>("AwayExpectedGoals")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int?>("AwayFouls")
                        .HasColumnType("int");

                    b.Property<int?>("AwayGoalKicks")
                        .HasColumnType("int");

                    b.Property<int?>("AwayGoalkeeperSaves")
                        .HasColumnType("int");

                    b.Property<int?>("AwayOffsides")
                        .HasColumnType("int");

                    b.Property<int?>("AwayPossession")
                        .HasColumnType("int");

                    b.Property<int?>("AwayRedCards")
                        .HasColumnType("int");

                    b.Property<int?>("AwayShotsOffTarget")
                        .HasColumnType("int");

                    b.Property<int?>("AwayShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<int?>("AwayThrowIns")
                        .HasColumnType("int");

                    b.Property<int?>("AwayYellowCards")
                        .HasColumnType("int");

                    b.Property<int?>("AwayYellowRedCards")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("HomeBlockedShots")
                        .HasColumnType("int");

                    b.Property<int?>("HomeCorners")
                        .HasColumnType("int");

                    b.Property<int?>("HomeCounterAttacks")
                        .HasColumnType("int");

                    b.Property<int?>("HomeCrosses")
                        .HasColumnType("int");

                    b.Property<decimal?>("HomeExpectedGoals")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int?>("HomeFouls")
                        .HasColumnType("int");

                    b.Property<int?>("HomeGoalKicks")
                        .HasColumnType("int");

                    b.Property<int?>("HomeGoalkeeperSaves")
                        .HasColumnType("int");

                    b.Property<int?>("HomeOffsides")
                        .HasColumnType("int");

                    b.Property<int?>("HomePossession")
                        .HasColumnType("int");

                    b.Property<int?>("HomeRedCards")
                        .HasColumnType("int");

                    b.Property<int?>("HomeShotsOffTarget")
                        .HasColumnType("int");

                    b.Property<int?>("HomeShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<int?>("HomeThrowIns")
                        .HasColumnType("int");

                    b.Property<int?>("HomeYellowCards")
                        .HasColumnType("int");

                    b.Property<int?>("HomeYellowRedCards")
                        .HasColumnType("int");

                    b.Property<string>("LiveScoreEventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("LiveScoreEventId")
                        .IsUnique();

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("MatchStatistics");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.PerformanceRatingRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EloRatingRunId")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MatchCount")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxAdjustment")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("ProcessedTeams")
                        .HasColumnType("int");

                    b.Property<decimal>("Scale")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EloRatingRunId");

                    b.HasIndex("TournamentId", "StartedAtUtc");

                    b.ToTable("PerformanceRatingRuns");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.SquadPlayerSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ContractUntil")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("ExternalPlayerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Foot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateOnly?>("JoinedDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("MarketValueEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MarketValueText")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Nationalities")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PositionGroup")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ProfileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ShirtNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("SignedFromClubName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SignedFromExternalClubId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SignedFromSeasonId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("SquadQualitySnapshotId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TransferFeeEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransferFeeText")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("TransferMovementText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("SquadQualitySnapshotId", "ExternalPlayerId");

                    b.ToTable("SquadPlayerSnapshots");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.SquadQualitySnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AverageAge")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("AverageMarketValueEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClubName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExternalSlug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ExternalTeamId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ExternalTeamMappingId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ForeignersCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("ForeignersPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("InLeagueSince")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LeagueLevel")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("NationalTeamPlayers")
                        .HasColumnType("int");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Season")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("SquadSize")
                        .HasColumnType("int");

                    b.Property<int?>("StadiumCapacity")
                        .HasColumnType("int");

                    b.Property<string>("StadiumName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TopElevenMarketValueEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TopFifteenMarketValueEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalMarketValueEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransferRecordText")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal?>("TransferRecordValueEur")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValueWeightedAverageAge")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("ValueWeightedContractYears")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalTeamMappingId", "FetchedAtUtc");

                    b.HasIndex("TeamId", "Provider", "FetchedAtUtc");

                    b.ToTable("SquadQualitySnapshots");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LiveScoreTeamId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("LiveScoreTeamId")
                        .IsUnique()
                        .HasFilter("[LiveScoreTeamId] IS NOT NULL");

                    b.HasIndex("Name");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.TeamEloRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EloRatingRunId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastMatchUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MatchesPlayed")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("EloRatingRunId", "TeamId")
                        .IsUnique();

                    b.ToTable("TeamEloRatings");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.TeamFormMatchSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Actual")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal>("Delta")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("Expected")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("FormRatingRunId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHome")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("KickoffUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LiveScoreEventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("MatchEloSnapshotId")
                        .HasColumnType("int");

                    b.Property<int>("OpponentTeamId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("WeightedDelta")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.HasKey("Id");

                    b.HasIndex("MatchEloSnapshotId");

                    b.HasIndex("OpponentTeamId");

                    b.HasIndex("TeamId");

                    b.HasIndex("FormRatingRunId", "MatchEloSnapshotId", "TeamId")
                        .IsUnique();

                    b.HasIndex("FormRatingRunId", "TeamId", "KickoffUtc");

                    b.ToTable("TeamFormMatchSnapshots");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.TeamFormRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AverageDelta")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("FormAdjustment")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("FormRatingRunId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastMatchUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MatchCount")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("WeightedActual")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("WeightedDelta")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("WeightedExpected")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("FormRatingRunId", "TeamId")
                        .IsUnique();

                    b.ToTable("TeamFormRatings");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.TeamPerformanceMatchSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DataCoverage")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("FoulStressScore")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("GoalkeeperStressScore")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int?>("HistoricalMatchStatisticsId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHome")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("KickoffUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LiveScoreEventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("MatchEloSnapshotId")
                        .HasColumnType("int");

                    b.Property<int?>("MatchStatisticsId")
                        .HasColumnType("int");

                    b.Property<decimal?>("OffsidesScore")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("OpponentTeamId")
                        .HasColumnType("int");

                    b.Property<int>("PerformanceRatingRunId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PossessionScore")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("RawPerformanceScore")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("ShotQualityScore")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("ShotScore")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("ShotsOnTargetScore")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TerritoryScore")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("WeightedPerformanceScore")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("XgScore")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.HasKey("Id");

                    b.HasIndex("HistoricalMatchStatisticsId");

                    b.HasIndex("MatchEloSnapshotId");

                    b.HasIndex("MatchStatisticsId");

                    b.HasIndex("OpponentTeamId");

                    b.HasIndex("TeamId");

                    b.HasIndex("PerformanceRatingRunId", "MatchEloSnapshotId", "TeamId")
                        .IsUnique();

                    b.HasIndex("PerformanceRatingRunId", "TeamId", "KickoffUtc");

                    b.ToTable("TeamPerformanceMatchSnapshots");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.TeamPerformanceRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DataCoverage")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<DateTimeOffset?>("LastMatchUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MatchCount")
                        .HasColumnType("int");

                    b.Property<decimal>("PerformanceAdjustment")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<int>("PerformanceRatingRunId")
                        .HasColumnType("int");

                    b.Property<decimal>("RawPerformanceScore")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("PerformanceRatingRunId", "TeamId")
                        .IsUnique();

                    b.ToTable("TeamPerformanceRatings");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiBaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CategoryTransliteratedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompetitionCountry")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("CompetitionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompetitionUrlName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FixturesUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("LastSyncedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LiveScoreCompetitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ResultsUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TimezoneOffset")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BaseUrl")
                        .IsUnique();

                    b.HasIndex("LiveScoreCompetitionId")
                        .IsUnique();

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.TournamentStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LiveScoreStageId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "LiveScoreStageId")
                        .IsUnique();

                    b.ToTable("TournamentStages");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.TournamentSyncRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("FinishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("InsertedMatches")
                        .HasColumnType("int");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("UnchangedMatches")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedMatches")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "StartedAtUtc");

                    b.ToTable("TournamentSyncRuns");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.TournamentTeam", b =>
                {
                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FirstSeenAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("TournamentId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("TournamentTeams");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.EloRatingRun", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.ExternalTeamMapping", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.Team", "Team")
                        .WithMany("ExternalMappings")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.FormRatingRun", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.EloRatingRun", "EloRatingRun")
                        .WithMany()
                        .HasForeignKey("EloRatingRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballResults.Api.Model.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EloRatingRun");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.HistoricalMatch", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FootballResults.Api.Model.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.HistoricalMatchStatistics", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.HistoricalMatch", "HistoricalMatch")
                        .WithOne("Statistics")
                        .HasForeignKey("FootballResults.Api.Model.Entities.HistoricalMatchStatistics", "HistoricalMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoricalMatch");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.Match", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FootballResults.Api.Model.Entities.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FootballResults.Api.Model.Entities.TournamentStage", "Stage")
                        .WithMany("Matches")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FootballResults.Api.Model.Entities.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Stage");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.MatchEloSnapshot", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballResults.Api.Model.Entities.EloRatingRun", "EloRatingRun")
                        .WithMany("MatchSnapshots")
                        .HasForeignKey("EloRatingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballResults.Api.Model.Entities.HistoricalMatch", "HistoricalMatch")
                        .WithMany("EloSnapshots")
                        .HasForeignKey("HistoricalMatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballResults.Api.Model.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("EloRatingRun");

                    b.Navigation("HistoricalMatch");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.MatchStatistics", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.Match", "Match")
                        .WithOne("Statistics")
                        .HasForeignKey("FootballResults.Api.Model.Entities.MatchStatistics", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.PerformanceRatingRun", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.EloRatingRun", "EloRatingRun")
                        .WithMany()
                        .HasForeignKey("EloRatingRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballResults.Api.Model.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EloRatingRun");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.SquadPlayerSnapshot", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.SquadQualitySnapshot", "SquadQualitySnapshot")
                        .WithMany("Players")
                        .HasForeignKey("SquadQualitySnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SquadQualitySnapshot");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.SquadQualitySnapshot", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.ExternalTeamMapping", "ExternalTeamMapping")
                        .WithMany()
                        .HasForeignKey("ExternalTeamMappingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballResults.Api.Model.Entities.Team", "Team")
                        .WithMany("SquadQualitySnapshots")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExternalTeamMapping");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.TeamEloRating", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.EloRatingRun", "EloRatingRun")
                        .WithMany("TeamRatings")
                        .HasForeignKey("EloRatingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballResults.Api.Model.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EloRatingRun");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.TeamFormMatchSnapshot", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.FormRatingRun", "FormRatingRun")
                        .WithMany("MatchSnapshots")
                        .HasForeignKey("FormRatingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballResults.Api.Model.Entities.MatchEloSnapshot", "MatchEloSnapshot")
                        .WithMany()
                        .HasForeignKey("MatchEloSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballResults.Api.Model.Entities.Team", "OpponentTeam")
                        .WithMany()
                        .HasForeignKey("OpponentTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballResults.Api.Model.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FormRatingRun");

                    b.Navigation("MatchEloSnapshot");

                    b.Navigation("OpponentTeam");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.TeamFormRating", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.FormRatingRun", "FormRatingRun")
                        .WithMany("TeamRatings")
                        .HasForeignKey("FormRatingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballResults.Api.Model.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormRatingRun");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.TeamPerformanceMatchSnapshot", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.HistoricalMatchStatistics", "HistoricalMatchStatistics")
                        .WithMany()
                        .HasForeignKey("HistoricalMatchStatisticsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FootballResults.Api.Model.Entities.MatchEloSnapshot", "MatchEloSnapshot")
                        .WithMany()
                        .HasForeignKey("MatchEloSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballResults.Api.Model.Entities.MatchStatistics", "MatchStatistics")
                        .WithMany()
                        .HasForeignKey("MatchStatisticsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FootballResults.Api.Model.Entities.Team", "OpponentTeam")
                        .WithMany()
                        .HasForeignKey("OpponentTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballResults.Api.Model.Entities.PerformanceRatingRun", "PerformanceRatingRun")
                        .WithMany("MatchSnapshots")
                        .HasForeignKey("PerformanceRatingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballResults.Api.Model.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HistoricalMatchStatistics");

                    b.Navigation("MatchEloSnapshot");

                    b.Navigation("MatchStatistics");

                    b.Navigation("OpponentTeam");

                    b.Navigation("PerformanceRatingRun");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.TeamPerformanceRating", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.PerformanceRatingRun", "PerformanceRatingRun")
                        .WithMany("TeamRatings")
                        .HasForeignKey("PerformanceRatingRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballResults.Api.Model.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformanceRatingRun");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.TournamentStage", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.Tournament", "Tournament")
                        .WithMany("Stages")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.TournamentSyncRun", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.Tournament", "Tournament")
                        .WithMany("SyncRuns")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.TournamentTeam", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.Team", "Team")
                        .WithMany("TournamentTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballResults.Api.Model.Entities.Tournament", "Tournament")
                        .WithMany("TournamentTeams")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballResults.Api.Model.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FootballResults.Api.Model.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.EloRatingRun", b =>
                {
                    b.Navigation("MatchSnapshots");

                    b.Navigation("TeamRatings");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.FormRatingRun", b =>
                {
                    b.Navigation("MatchSnapshots");

                    b.Navigation("TeamRatings");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.HistoricalMatch", b =>
                {
                    b.Navigation("EloSnapshots");

                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.Match", b =>
                {
                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.PerformanceRatingRun", b =>
                {
                    b.Navigation("MatchSnapshots");

                    b.Navigation("TeamRatings");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.SquadQualitySnapshot", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("ExternalMappings");

                    b.Navigation("HomeMatches");

                    b.Navigation("SquadQualitySnapshots");

                    b.Navigation("TournamentTeams");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.Tournament", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Stages");

                    b.Navigation("SyncRuns");

                    b.Navigation("TournamentTeams");
                });

            modelBuilder.Entity("FootballResults.Api.Model.Entities.TournamentStage", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
