namespace FootballResults.Api.DTOs;

public sealed record ImportTransfermarktSquadRequest(
    string TransfermarktUrl,
    string? Season = null);

public sealed record ImportTransfermarktSquadResponse(
    int TeamId,
    string TeamName,
    int MappingId,
    int SnapshotId,
    string ExternalTeamId,
    string ExternalSlug,
    string ClubName,
    string SourceUrl,
    string? Season,
    int PlayerCount,
    decimal? TotalMarketValueEur,
    decimal? TopElevenMarketValueEur,
    decimal? TopFifteenMarketValueEur,
    decimal? ValueWeightedAverageAge,
    decimal? ValueWeightedContractYears);

public sealed record ExternalTeamMappingDto(
    int Id,
    int TeamId,
    string TeamName,
    string Provider,
    string ExternalTeamId,
    string ExternalSlug,
    string SourceUrl,
    DateTimeOffset CreatedAtUtc,
    DateTimeOffset UpdatedAtUtc);

public sealed record SquadQualitySnapshotDto(
    int Id,
    int TeamId,
    string TeamName,
    string TeamAbbreviation,
    string Provider,
    string ExternalTeamId,
    string ExternalSlug,
    string SourceUrl,
    string? Season,
    DateTimeOffset FetchedAtUtc,
    string ClubName,
    string LeagueName,
    string LeagueLevel,
    string InLeagueSince,
    string StadiumName,
    int? StadiumCapacity,
    string TransferRecordText,
    decimal? TransferRecordValueEur,
    int? SquadSize,
    decimal? AverageAge,
    int? ForeignersCount,
    decimal? ForeignersPercentage,
    int? NationalTeamPlayers,
    decimal? TotalMarketValueEur,
    decimal? AverageMarketValueEur,
    decimal? TopElevenMarketValueEur,
    decimal? TopFifteenMarketValueEur,
    decimal? ValueWeightedAverageAge,
    decimal? ValueWeightedContractYears,
    int PlayerCount);

public sealed record SquadPlayerSnapshotDto(
    int Id,
    int SquadQualitySnapshotId,
    string ExternalPlayerId,
    string ProfileUrl,
    string PlayerName,
    string PositionGroup,
    string Position,
    string ShirtNumber,
    DateOnly? DateOfBirth,
    int? Age,
    string Nationalities,
    decimal? HeightCm,
    string Foot,
    DateOnly? JoinedDate,
    string SignedFromClubName,
    string SignedFromExternalClubId,
    string SignedFromSeasonId,
    string TransferMovementText,
    string TransferFeeText,
    decimal? TransferFeeEur,
    DateOnly? ContractUntil,
    string MarketValueText,
    decimal? MarketValueEur);

public sealed record TeamSquadQualityRatingDto(
    int TeamId,
    string TeamName,
    string TeamAbbreviation,
    int? SnapshotId,
    DateTimeOffset? FetchedAtUtc,
    decimal? TotalMarketValueEur,
    decimal? TopElevenMarketValueEur,
    decimal? TopFifteenMarketValueEur,
    decimal? AverageAge,
    decimal? ValueWeightedAverageAge,
    decimal? ValueWeightedContractYears,
    int? NationalTeamPlayers,
    int PlayerCount,
    decimal? TopElevenScore,
    decimal? TopFifteenScore,
    decimal? TotalValueScore,
    decimal? NationalTeamPlayersScore,
    decimal? PrimeAgeScore,
    decimal? ContractStabilityScore,
    decimal? PositionalBalanceScore,
    decimal SquadQualityScore,
    decimal SquadQualityAdjustment);
